Repository tokend/web-client, pull requests merged in 2019-04, with the labels that each got.

#198 [TDV-263] Fix displaying long strings inside cards
  CHANGELOG.md
  src/vue/common/assets/AssetsList.vue
  src/vue/pages/SaleDetails.vue
  src/vue/pages/sales/SaleCard.vue
Labels: bug

#209 [TDV-166] Display negative amounts on balance effect viewers
  CHANGELOG.md
  src/i18n/en.json
  src/vue/modules/movements-history/components/effect-viewers/balance-changed.vue
  src/vue/modules/movements-history/components/effect-viewers/particular-balance-changed.vue
  src/vue/modules/movements-history/components/movement-attributes-viewer.vue
Labels: bug

#215 [TDV-385] Fix movements unit tests
  CHANGELOG.md
  src/vue/modules/movements-history/index.spec.js
Labels: bug

#217 [TDV-391] Fix setting account role on KYC forms
  CHANGELOG.md
  src/js/records/requests/change-role.record.js
  src/vue/mixins/verification-form.mixin.js
Labels: bug

#211 [TDV-147] Integrate account role resetting
  CHANGELOG.md
  src/i18n/en.json
  src/js/records/requests/change-role.record.js
  src/vue/pages/Verification.vue
  src/vue/pages/VerificationCorporate.vue
  src/vue/pages/VerificationGeneral.vue
  src/vuex/kyc.module.js
  src/vuex/kyc.spec.js
  src/vuex/types.js
Labels: enhancement

#219 [TDV-398] Convert account role ID to number
  CHANGELOG.md
  src/vuex/account.e2e.js
  src/vuex/account.module.js
Labels: bug

#227 [TDL-62] Update invoice amount decimal digits
  CHANGELOG.md
  src/vue/modules/loyalty-points/create-invoice-form/index.vue
  src/vue/modules/loyalty-points/loyalty-points-invoices/index.vue
Labels: enhancement

#223 [TDL-44] Add subject field to the invoice form
  CHANGELOG.md
  src/modules-arch/schemes/loyalty-points-merchant.en.json
  src/vue/modules/loyalty-points/create-invoice-form/index.vue
  src/vue/modules/loyalty-points/loyalty-points-invoices/index.vue
Labels: enhancement, loyalty

#230 [TDL-38] Display invoice state & summary
  CHANGELOG.md
  src/modules-arch/schemes/loyalty-points-merchant.en.json
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-state-viewer.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-summary-viewer.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-viewer.vue
  src/vue/modules/loyalty-points/create-invoice-form/const/payment-states.js
  src/vue/modules/loyalty-points/create-invoice-form/index.vue
  src/vue/modules/loyalty-points/create-invoice-form/wrappers/invoice.js
Labels: enhancement, loyalty

#226 [TDL-36, TDL-41] Loyalty history improvements
  CHANGELOG.md
  src/i18n/en.json
  src/modules-arch/schemes/loyalty-points-merchant.en.json
  src/modules-arch/schemes/loyalty-points-reconciliation.en.json
  src/modules-arch/schemes/loyalty-points-reconciliation.js
  src/vue/modules/movements-history/components/effect-viewers/balance-changed.vue
  src/vue/modules/movements-history/components/effect-viewers/particular-balance-changed.vue
  src/vue/modules/movements-history/components/movement-attributes-viewer.vue
  src/vue/modules/movements-history/components/movement-summary-viewer.vue
  src/vue/modules/movements-history/components/movements-table-row.vue
  src/vue/modules/movements-history/components/movements-table.vue
  src/vue/modules/movements-history/components/operation-viewers/payment.vue
  src/vue/modules/movements-history/mixins/translation-filters.mixin.js
Labels: enhancement, loyalty

#222 [TDL-42] Change chart statistics asset
  CHANGELOG.md
  src/vue/modules/loyalty-points/loyalty-points-statistics/components/viewers/payable-overtime-viewer.vue
  src/vue/modules/loyalty-points/loyalty-points-statistics/components/viewers/receivable-overtime-viewer.vue
Labels: enhancement, loyalty

#239 [TDL-64] Fix setting merchant account ID to invoice URL
  CHANGELOG.md
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-viewer.vue
Labels: bug, loyalty

#221 [TDV-188] Create asset form module
  CHANGELOG.md
  src/i18n/en.json
  src/modules-arch/schemes/vanilla.js
  src/vue/modules/create-asset-form/_api.js
  src/vue/modules/create-asset-form/_config.js
  src/vue/modules/create-asset-form/components/advanced-step-form.spec.js
  src/vue/modules/create-asset-form/components/advanced-step-form.vue
  src/vue/modules/create-asset-form/components/information-step-form.spec.js
  src/vue/modules/create-asset-form/components/information-step-form.vue
  src/vue/modules/create-asset-form/index.spec.js
  src/vue/modules/create-asset-form/index.vue
  src/vue/modules/create-asset-form/mixins/load-asset-types.mixin.js
  src/vue/modules/create-asset-form/mixins/load-asset-types.mixin.spec.js
  src/vue/modules/create-asset-form/mixins/manage-asset-request.mixin.js
  src/vue/modules/create-asset-form/mixins/manage-asset-request.mixin.spec.js
  src/vue/modules/create-asset-form/mixins/upload-documents.mixin.js
  src/vue/modules/create-asset-form/mixins/upload-documents.mixin.spec.js
  src/vue/modules/create-asset-form/module.js
  src/vue/modules/create-asset-form/wrappers/create-asset-request.js
  src/vue/modules/create-asset-form/wrappers/create-asset-request.spec.js
  src/vue/pages/Assets.vue
  src/vue/pages/assets-page-module.js
Labels: modularization, vanilla

#241 [TDV-189] Update asset form module
  CHANGELOG.md
  src/i18n/en.json
  src/vue/modules/update-asset-form/_api.js
  src/vue/modules/update-asset-form/_config.js
  src/vue/modules/update-asset-form/components/advanced-step-form.spec.js
  src/vue/modules/update-asset-form/components/advanced-step-form.vue
  src/vue/modules/update-asset-form/components/information-step-form.spec.js
  src/vue/modules/update-asset-form/components/information-step-form.vue
  src/vue/modules/update-asset-form/index.spec.js
  src/vue/modules/update-asset-form/index.vue
  src/vue/modules/update-asset-form/mixins/load-assets.mixin.js
  src/vue/modules/update-asset-form/mixins/load-assets.mixin.spec.js
  src/vue/modules/update-asset-form/mixins/manage-asset-request.mixin.js
  src/vue/modules/update-asset-form/mixins/manage-asset-request.mixin.spec.js
  src/vue/modules/update-asset-form/mixins/upload-documents.mixin.js
  src/vue/modules/update-asset-form/mixins/upload-documents.mixin.spec.js
  src/vue/modules/update-asset-form/module.js
  src/vue/modules/update-asset-form/wrappers/asset.js
  src/vue/modules/update-asset-form/wrappers/asset.spec.js
  src/vue/modules/update-asset-form/wrappers/update-asset-request.js
  src/vue/modules/update-asset-form/wrappers/update-asset-request.spec.js
Labels: modularization, vanilla

#231 [TDQA-20] Display no balance message on trade form
  CHANGELOG.md
  src/i18n/en.json
  src/modules-arch/schemes/reit-en.json
  src/vue/forms/SubmitTradeOfferForm.vue
Labels: bug, vanilla

#245 [TDV-520] Fix displaying QR code & clipboard field
  CHANGELOG.md
  src/vue/fields/ClipboardField.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-viewer.vue
  src/vue/pages/Signup.vue
Labels: bug, vanilla

#233 [TDV-337] Fixed a bug with cannot invest if asset balance is 0 on Invest form
  CHANGELOG.md
  src/i18n/en.json
  src/modules-arch/schemes/reit-en.json
  src/vue/forms/InvestForm.vue
Labels: bug

#247 [TDV-449] Display verification request success message
  CHANGELOG.md
  src/i18n/en.json
  src/vue/pages/VerificationCorporate.vue
  src/vue/pages/VerificationGeneral.vue
Labels: bug, enhancement

#255 [TDV-349] Display asset code in fee bounds
  CHANGELOG.md
  src/vue/modules/fees/components/fees-table.vue
Labels: bug

#259 [TDV-163] Fix KYC required translations on invest form
  CHANGELOG.md
  src/i18n/en.json
  src/modules-arch/schemes/reit-en.json
  src/vue/forms/InvestForm.vue
Labels: bug

#262 [TDV-151] Fix form tabs disabled state
  CHANGELOG.md
  src/vue/common/FormStepper.vue
Labels: bug

#274 [TDV-582] Redesign verification message viewer
  CHANGELOG.md
  src/i18n/en.json
  src/scss/variables.scss
  src/vue/pages/Verification.vue
  src/vue/pages/verification/VerificationStateMessage.vue
Labels: enhancement

#275 [TDV-594] Fix trade history margins
  CHANGELOG.md
  src/vue/pages/TradeExchange.vue
Labels: bug

#276 [TDV-587] Fix displaying input field label on Firefox
  CHANGELOG.md
  src/vue/fields/InputField.vue
Labels: bug

#260 [TDV-259] Restore 2FA
  CHANGELOG.md
  src/i18n/en.json
  src/vue/forms/ChangePasswordForm.vue
  src/vue/forms/LoginForm.vue
  src/vue/forms/TfaForm.vue
  src/vue/pages/Security.vue
Labels: enhancement

#263 [TDV-357] Remove id attributes from html elements
  CHANGELOG.md
  src/vue/common/chart/Chart.Renderer.vue
  src/vue/common/chart/Chart.vue
  src/vue/forms/ChangePasswordForm.vue
  src/vue/forms/CreateSaleForm.vue
  src/vue/forms/InvestForm.vue
  src/vue/forms/IssuanceForm.spec.js
  src/vue/forms/IssuanceForm.vue
  src/vue/forms/LimitsForm.vue
  src/vue/forms/LoginForm.spec.js
  src/vue/forms/LoginForm.vue
  src/vue/forms/RecoveryForm.spec.js
  src/vue/forms/RecoveryForm.vue
  src/vue/forms/SignupForm.spec.js
  src/vue/forms/SignupForm.vue
  src/vue/forms/TransferForm.vue
  src/vue/forms/WithdrawalForm.vue
  src/vue/modules/coinpayments-deposit/components/coinpayments-form.spec.js
  src/vue/modules/coinpayments-deposit/components/coinpayments-form.vue
  src/vue/modules/create-opportunity/index.vue
  src/vue/modules/deposit-fiat-card/index.vue
  src/vue/modules/dividend-form/index.vue
  src/vue/modules/documents/document-manager/modules/signers-manager/components/manage-signer-form.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-viewer.vue
  src/vue/modules/loyalty-points/loyalty-points-statistics/components/charts/line-chart.vue
  src/vue/modules/loyalty-points/loyalty-points-statistics/components/charts/pie-chart.vue
  src/vue/modules/loyalty-points/loyalty-points-statistics/components/viewers/payable-overtime-viewer.vue
  src/vue/modules/loyalty-points/loyalty-points-statistics/components/viewers/payable-receivable-viewer.vue
  src/vue/modules/loyalty-points/loyalty-points-statistics/components/viewers/receivable-distribution-viewer.vue
  src/vue/modules/loyalty-points/loyalty-points-statistics/components/viewers/receivable-overtime-viewer.vue
  src/vue/modules/withdrawal-fiat-bank/index.vue
  src/vue/modules/withdrawal-fiat-card/index.vue
  src/vue/pages/VerificationCorporate.vue
  src/vue/pages/VerificationGeneral.vue
Labels: enhancement

#256 [TDV-209, TDV-210, TDV-211] Use wallet public key for pre-issuance
  CHANGELOG.md
  src/i18n/en.json
  src/vue/modules/create-asset-form/components/advanced-step-form.spec.js
  src/vue/modules/create-asset-form/components/advanced-step-form.vue
  src/vue/modules/create-asset-form/index.vue
  src/vue/modules/create-asset-form/wrappers/create-asset-request.js
  src/vue/modules/create-asset-form/wrappers/create-asset-request.spec.js
Labels: bug, enhancement

#272 [TDV-148] Blocking the account
  CHANGELOG.md
  src/i18n/en.json
  src/js/records/requests/change-role.record.js
  src/vue/mixins/verification-form.mixin.js
  src/vue/navigation/Passport.vue
  src/vue/pages/Verification.vue
  src/vue/pages/VerificationCorporate.vue
  src/vue/pages/VerificationGeneral.vue
  src/vue/pages/verification/VerificationStateMessage.vue
  src/vuex/account.module.js
  src/vuex/key-value.module.js
  src/vuex/kyc.e2e.js
  src/vuex/kyc.module.js
  src/vuex/kyc.spec.js
  src/vuex/types.js
Labels: enhancement

#281 [TDV-621] Remove buttons' 'form' attribute
  CHANGELOG.md
  src/vue/forms/ChangePasswordForm.vue
  src/vue/forms/LoginForm.vue
  src/vue/forms/TfaForm.vue
  src/vue/forms/TransferForm.vue
  src/vue/forms/WithdrawalForm.vue
  src/vue/modules/coinpayments-deposit/components/coinpayments-form.vue
  src/vue/modules/deposit-fiat-card/index.vue
  src/vue/modules/dividend-form/index.vue
  src/vue/modules/requests/incoming-withdrawal-requests/components/reject-request-form.spec.js
  src/vue/modules/requests/incoming-withdrawal-requests/components/reject-request-form.vue
  src/vue/modules/withdrawal-fiat-bank/index.vue
  src/vue/pages/VerificationCorporate.vue
  src/vue/pages/VerificationGeneral.vue
Labels: bug

#264 [TDV-258] Get blob types from SDK
  CHANGELOG.md
  src/js/const/blob-types.const.js
  src/vue/forms/CreateSaleForm.vue
  src/vue/modules/create-opportunity/index.vue
  src/vue/pages/VerificationCorporate.vue
  src/vue/pages/VerificationGeneral.vue
Labels: enhancement

#289 [TDQA-37] Fix displaying KYC verification code
  CHANGELOG.md
  src/vue/pages/VerificationGeneral.vue
Labels: bug

#290 [TDQA-37] Fix paying fees for recipient
  CHANGELOG.md
  src/vue/forms/TransferForm.vue
Labels: bug

#288 [TDL-75, TDL-76, TDL-77] New statistics charts
  CHANGELOG.md
  src/modules-arch/schemes/loyalty-points-reconciliation.en.json
  src/vue/common/chart/Chart.Renderer.vue
  src/vue/common/chart/Chart.Tabs.vue
  src/vue/modules/loyalty-points/loyalty-points-statistics/components/charts/line-chart.vue
  src/vue/modules/loyalty-points/loyalty-points-statistics/components/charts/pie-chart.vue
  src/vue/modules/loyalty-points/loyalty-points-statistics/components/viewers/payable-distribution-viewer.vue
  src/vue/modules/loyalty-points/loyalty-points-statistics/components/viewers/payable-receivable-viewer.vue
  src/vue/modules/loyalty-points/loyalty-points-statistics/components/viewers/receivable-payable-viewer.vue
  src/vue/modules/loyalty-points/loyalty-points-statistics/index.vue
  src/vue/modules/loyalty-points/loyalty-points-statistics/mocks/payable-distribution.json
  src/vue/modules/loyalty-points/loyalty-points-statistics/mocks/receivable-distribution.json
  src/vue/modules/loyalty-points/loyalty-points-statistics/mocks/receivable-overtime.json
  src/vue/modules/loyalty-points/loyalty-points-statistics/mocks/receivable-payable.json
Labels: enhancement, loyalty

#285 [TDL-71, TDL-72, TDL-73, TDL-74] New invoice flow
  CHANGELOG.md
  src/i18n/en.json
  src/modules-arch/schemes/loyalty-points-merchant.en.json
  src/vue/modules/loyalty-points/create-invoice-form/_api.js
  src/vue/modules/loyalty-points/create-invoice-form/_config.js
  src/vue/modules/loyalty-points/create-invoice-form/components/confirmation-state-viewer.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-confirmation.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-form.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-summary-viewer.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-viewer.vue
  src/vue/modules/loyalty-points/create-invoice-form/index.vue
  src/vue/modules/loyalty-points/create-invoice-form/store/index.js
  src/vue/modules/loyalty-points/create-invoice-form/wrappers/asset-pair.js
  src/vue/modules/loyalty-points/create-invoice-form/wrappers/asset.js
  src/vue/modules/loyalty-points/create-invoice-form/wrappers/invoice.js
Labels: enhancement, loyalty

#297 [TDL-81] Fix invoice polling
  CHANGELOG.md
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-confirmation.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-form.vue
Labels: bug, loyalty

#300 [TDL-82] Fix invoice transaction source account
  CHANGELOG.md
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-form.vue
Labels: bug, loyalty

#238 [TDV-316] Feature: Flatpickr implementation not via "vue-flatpickr-component", but via pure "flatpickr" library
  CHANGELOG.md
  package.json
  src/vue/fields/DateField.vue
  src/vue/forms/CreateSaleForm.vue
  src/vue/forms/DepositForm.vue
  yarn.lock
Labels: bug, enhancement

#304 [TDL-83] Fix reconciliation withdrawal requests
  CHANGELOG.md
  src/i18n/en.json
  src/modules-arch/schemes/loyalty-points-reconciliation.js
  src/vue/modules/requests/incoming-withdrawal-requests/components/requests-table.vue
Labels: bug, loyalty

#306 [TDL-87, TDL-88] Select invoice point by loyalty account number
  CHANGELOG.md
  src/vue/modules/loyalty-points/create-invoice-form/_config.js
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-form.vue
  src/vue/modules/loyalty-points/create-invoice-form/const/payment-states.const.js
  src/vue/modules/loyalty-points/create-invoice-form/const/point-codes.const.js
  src/vue/modules/loyalty-points/create-invoice-form/wrappers/invoice.js
Labels: enhancement, loyalty

#307 [TDL-84] Show zero axis line on chart
  CHANGELOG.md
  src/vue/common/chart/Chart.Renderer.vue
Labels: enhancement

#312 [TDV-665] Add selected asset to page URL
  CHANGELOG.md
  src/vue/modules/movements-top-bar/index.vue
  src/vue/pages/Dashboard.spec.js
  src/vue/pages/Dashboard.vue
  src/vue/pages/Fees.vue
  src/vue/pages/Limits.vue
Labels: enhancement

#314 [TDV-317] Use button classes instead of mixins
  CHANGELOG.md
  src/vue/common/CollectionLoader.vue
  src/vue/common/EmailGetter.vue
  src/vue/common/FormConfirmation.vue
  src/vue/common/chart/Chart.Tabs.vue
  src/vue/fields/ClipboardField.vue
  src/vue/forms/ChangePasswordForm.vue
  src/vue/forms/CreateTradeOfferForm.vue
  src/vue/forms/IssuanceForm.vue
  src/vue/forms/LoginForm.vue
  src/vue/forms/PreIssuanceForm.vue
  src/vue/forms/RecoveryForm.vue
  src/vue/forms/SignupForm.vue
  src/vue/forms/SubmitTradeOfferForm.vue
  src/vue/forms/TfaForm.vue
  src/vue/forms/TransferForm.vue
  src/vue/forms/_app-form.scss
  src/vue/forms/_auth-form.scss
  src/vue/modules/buy-back-form/index.vue
  src/vue/modules/redeem-form/index.vue
  src/vue/pages/Downloads.vue
  src/vue/pages/IosInstallationGuide.vue
  src/vue/pages/Signup.vue
  src/vue/pages/Terms.vue
  src/vue/pages/VerificationCorporate.vue
  src/vue/pages/VerificationGeneral.vue
  src/vue/pages/Verify.vue
  src/vue/pages/_auth-page.scss
  src/vue/pages/assets/AssetDetails.vue
Labels: bug

#313 [TDV-696] Fix account verification using e-mail link
  CHANGELOG.md
  src/vue-router/redirect.js
  src/vue/pages/Login.vue
Labels: bug

#315 [TDV-701] Open pre-issuance details link in new tab
  CHANGELOG.md
  src/i18n/en.json
Labels: enhancement
