Repository tokend/web-client, pull requests merged in 2019-05, with the labels that each got.

#296 [TDV-185] Pre-issuance form module
  CHANGELOG.md
  src/i18n/en.json
  src/modules-arch/pseudo-modules/pre-issuance-drawer-pseudo-module.js
  src/modules-arch/schemes/loyalty-points-reconciliation.js
  src/modules-arch/schemes/vanilla.js
  src/vue/forms/PreIssuanceForm.spec.js
  src/vue/forms/PreIssuanceForm.vue
  src/vue/modules/pre-issuance-form/_api.js
  src/vue/modules/pre-issuance-form/_errors.js
  src/vue/modules/pre-issuance-form/components/issuance-viewer.vue
  src/vue/modules/pre-issuance-form/components/upload-pre-issuance-form.spec.js
  src/vue/modules/pre-issuance-form/components/upload-pre-issuance-form.vue
  src/vue/modules/pre-issuance-form/index.spec.js
  src/vue/modules/pre-issuance-form/index.vue
  src/vue/modules/pre-issuance-form/mixins/load-owned-assets.mixin.js
  src/vue/modules/pre-issuance-form/mixins/load-owned-assets.mixin.spec.js
  src/vue/modules/pre-issuance-form/mixins/manage-pre-issuance.mixin.js
  src/vue/modules/pre-issuance-form/mixins/manage-pre-issuance.mixin.spec.js
  src/vue/modules/pre-issuance-form/module.js
  src/vue/modules/pre-issuance-form/wrappers/asset.js
  src/vue/modules/pre-issuance-form/wrappers/asset.spec.js
  src/vue/modules/pre-issuance-form/wrappers/issuance.js
  src/vue/modules/pre-issuance-form/wrappers/issuance.spec.js
  src/vue/pages/Issuance.vue
  src/vue/pages/issuance-page-module.js
Labels: modularization

#295 [TDV-184] Issuance form module
  CHANGELOG.md
  src/i18n/en.json
  src/js/errors/runtime-errors.js
  src/js/helpers/error-handler.js
  src/modules-arch/schemes/loyalty-points-merchant.en.json
  src/modules-arch/schemes/loyalty-points-merchant.js
  src/modules-arch/schemes/loyalty-points-reconciliation.js
  src/modules-arch/schemes/reit.js
  src/modules-arch/schemes/vanilla.js
  src/vue/forms/IssuanceForm.spec.js
  src/vue/forms/IssuanceForm.vue
  src/vue/modules/issuance-form/_api.js
  src/vue/modules/issuance-form/_config.js
  src/vue/modules/issuance-form/components/create-issuance-form.spec.js
  src/vue/modules/issuance-form/components/create-issuance-form.vue
  src/vue/modules/issuance-form/index.spec.js
  src/vue/modules/issuance-form/index.vue
  src/vue/modules/issuance-form/mixins/get-receiver-account.mixin.js
  src/vue/modules/issuance-form/mixins/get-receiver-account.mixin.spec.js
  src/vue/modules/issuance-form/mixins/load-owned-assets.mixin.js
  src/vue/modules/issuance-form/mixins/load-owned-assets.mixin.spec.js
  src/vue/modules/issuance-form/mixins/manage-issuance.mixin.js
  src/vue/modules/issuance-form/mixins/manage-issuance.mixin.spec.js
  src/vue/modules/issuance-form/module.js
  src/vue/modules/issuance-form/wrappers/asset.js
  src/vue/modules/issuance-form/wrappers/asset.spec.js
  src/vue/pages/Dashboard.spec.js
  src/vue/pages/Dashboard.vue
  src/vue/pages/Issuance.vue
  src/vue/pages/LoyaltyPoints.vue
  src/vue/pages/dashboard-page-module.js
  src/vue/pages/issuance-page-module.js
  src/vue/pages/loyalty-points-page-module.js
Labels: modularization

#254 [TDV-190, TDV-414] Create sale form module
  CHANGELOG.md
  src/i18n/en.json
  src/modules-arch/pseudo-modules/create-sale-pseudo-module.js
  src/modules-arch/schemes/reit-en.json
  src/modules-arch/schemes/vanilla.js
  src/scss/variables.scss
  src/vue/forms/CreateSaleForm.vue
  src/vue/modules/create-asset-form/mixins/manage-asset-request.mixin.js
  src/vue/modules/create-opportunity/index.vue
  src/vue/modules/create-opportunity/module.js
  src/vue/modules/create-sale-form/_api.js
  src/vue/modules/create-sale-form/_config.js
  src/vue/modules/create-sale-form/components/full-description-step-form.spec.js
  src/vue/modules/create-sale-form/components/full-description-step-form.vue
  src/vue/modules/create-sale-form/components/information-step-form.spec.js
  src/vue/modules/create-sale-form/components/information-step-form.vue
  src/vue/modules/create-sale-form/components/short-blurb-step-form.spec.js
  src/vue/modules/create-sale-form/components/short-blurb-step-form.vue
  src/vue/modules/create-sale-form/index.spec.js
  src/vue/modules/create-sale-form/index.vue
  src/vue/modules/create-sale-form/mixins/load-assets.mixin.js
  src/vue/modules/create-sale-form/mixins/load-assets.spec.js
  src/vue/modules/create-sale-form/mixins/manage-sale-description.mixin.js
  src/vue/modules/create-sale-form/mixins/manage-sale-description.mixin.spec.js
  src/vue/modules/create-sale-form/mixins/manage-sale-request.mixin.js
  src/vue/modules/create-sale-form/mixins/manage-sale-request.mixin.spec.js
  src/vue/modules/create-sale-form/mixins/upload-documents.mixin.js
  src/vue/modules/create-sale-form/mixins/upload-documents.mixin.spec.js
  src/vue/modules/create-sale-form/module.js
  src/vue/modules/create-sale-form/wrappers/asset.js
  src/vue/modules/create-sale-form/wrappers/asset.spec.js
  src/vue/modules/create-sale-form/wrappers/create-sale-request.js
  src/vue/modules/create-sale-form/wrappers/create-sale-request.spec.js
  src/vue/modules/requests/create-sale-requests/components/requests-renderer.vue
  src/vue/modules/requests/create-sale-requests/index.vue
  src/vue/modules/update-asset-form/mixins/manage-asset-request.mixin.js
  src/vue/pages/Sales.vue
  src/vue/pages/sales-page-module.js
Labels: modularization

#331 [TDV-807] Fix sale modules bugs
  CHANGELOG.md
  src/vue/modules/create-sale-form/components/full-description-step-form.vue
  src/vue/modules/create-sale-form/mixins/manage-sale-description.mixin.js
  src/vue/modules/create-sale-form/mixins/manage-sale-description.mixin.spec.js
  src/vue/pages/Sales.vue
  src/vue/pages/sales/AllSales.vue
Labels: bug

#326 [TDV-351] File field improvements
  CHANGELOG.md
  src/i18n/en.json
  src/js/utils/file.util.js
  src/scss/mixins.scss
  src/scss/variables.scss
  src/vue/fields/FileField.vue
  src/vue/fields/scss/_variables.scss
  src/vue/forms/CreateSaleForm.vue
  src/vue/forms/LimitsDocumentsUploaderForm.vue
  src/vue/forms/PreIssuanceForm.vue
  src/vue/modules/create-asset-form/components/advanced-step-form.vue
  src/vue/modules/create-asset-form/components/information-step-form.vue
  src/vue/modules/create-opportunity/index.vue
  src/vue/modules/create-sale-form/components/short-blurb-step-form.vue
  src/vue/modules/documents/document-upload-form/index.vue
  src/vue/modules/pre-issuance-form/components/upload-pre-issuance-form.vue
  src/vue/modules/update-asset-form/components/advanced-step-form.vue
  src/vue/modules/update-asset-form/components/information-step-form.vue
  src/vue/modules/verification/general-form/components/section-avatar.vue
  src/vue/modules/verification/general-form/components/section-country.vue
  src/vue/modules/verification/general-form/components/section-documents.vue
  src/vue/modules/verification/general-form/components/section-selfie.vue
  src/vue/pages/VerificationCorporate.vue
  src/vue/pages/VerificationGeneral.vue
Labels: enhancement

#329 [TDV-628] Feature: improve babelrc
  .babelrc
  CHANGELOG.md
Labels: enhancement

#338 [TDV-828] Fix uploading docs on verification page
  CHANGELOG.md
  src/vue/modules/verification/general-form/index.vue
  src/vue/modules/verification/general-form/store/index.js
  src/vue/modules/verification/general-form/store/upload-document-if-needed.js
  src/vue/pages/Verification.vue
Labels: bug

#339 [TDV-821] Fix caps lock modifier error
  CHANGELOG.md
  src/vue/fields/InputField.vue
Labels: bug

#309 [TDV-688] Sort balances by descending amount
  CHANGELOG.md
  src/vue/modules/assets/balance-explorer/index.vue
  src/vue/modules/assets/balance-explorer/store/index.e2e.js
  src/vue/modules/assets/balance-explorer/store/index.js
  src/vue/modules/assets/balance-explorer/store/index.spec.js
  src/vue/pages/Balances.vue
Labels: enhancement

#344 [TDV-860] Display quote asset on chart
  CHANGELOG.md
  src/vue/common/chart/Chart.vue
Labels: bug

#345 [TDV-797] Show disabled investing reason using message box
  CHANGELOG.md
  src/i18n/en.json
  src/vue/common/MessageBox.vue
  src/vue/forms/InvestForm.vue
Labels: enhancement

#342 [TDV-624] Whitelist management
  CHANGELOG.md
  src/i18n/en.json
  src/js/const/sale-definition-types.const.js
  src/js/records/entities/sale.record.js
  src/modules-arch/schemes/reit-en.json
  src/modules-arch/schemes/reit.js
  src/modules-arch/schemes/vanilla.js
  src/vue-router/routes.js
  src/vue/common/tabs/Tabs.vue
  src/vue/forms/InvestForm.vue
  src/vue/forms/WhitelistInviteForm.vue
  src/vue/modules/create-sale-form/components/information-step-form.vue
  src/vue/modules/create-sale-form/index.vue
  src/vue/modules/create-sale-form/mixins/load-assets.mixin.js
  src/vue/modules/create-sale-form/mixins/load-assets.spec.js
  src/vue/modules/create-sale-form/mixins/manage-sale-request.mixin.js
  src/vue/modules/create-sale-form/mixins/manage-sale-request.mixin.spec.js
  src/vue/modules/create-sale-form/wrappers/asset.js
  src/vue/modules/create-sale-form/wrappers/asset.spec.js
  src/vue/modules/create-sale-form/wrappers/create-sale-request.js
  src/vue/modules/create-sale-form/wrappers/create-sale-request.spec.js
  src/vue/modules/requests/create-sale-requests/wrappers/create-sale-request.js
  src/vue/modules/requests/create-sale-requests/wrappers/create-sale-request.spec.js
  src/vue/pages/SaleDetails.vue
  src/vue/pages/Sales.vue
  src/vue/pages/sale-details/SaleCampaignViewer.vue
  src/vue/pages/sale-details/SaleOverviewDetails.vue
  src/vue/pages/sale-details/SaleStateWidget.vue
  src/vue/pages/sale-details/SaleStatisticsViewer.vue
  src/vue/pages/sale-details/SaleWhitelistManager.vue
  src/vue/pages/sale-details/whitelist/WhitelistInvitationsList.vue
  src/vue/pages/sales-page-module.js
  src/vue/pages/sales/SalesList.vue
  src/vue/pages/sales/investable-sales-page-module.js
  src/vue/pages/sales/user-owned-sales-page-module.js
Labels: enhancement

#358 [TDV-910] Fix displaying assets list on balances page
  CHANGELOG.md
  src/vue/modules/assets/balance-explorer/store/index.js
  src/vue/modules/assets/balance-explorer/store/index.spec.js
Labels: bug

#360 [TDV-937] Load converted account balances in account module
  CHANGELOG.md
  src/test/mocks/account-balances-details.json
  src/vue/navigation/Passport.Balances.vue
  src/vuex/account.module.js
  src/vuex/account.spec.js
Labels: enhancement

#362 [TDV-924] Assets vuex module
  CHANGELOG.md
  src/js/records/entities/asset.record.js
  src/js/records/entities/balance.record.js
  src/vue/common/TradeTopBar.vue
  src/vue/forms/DepositForm.vue
  src/vue/forms/InvestForm.vue
  src/vue/forms/TransferForm.spec.js
  src/vue/forms/TransferForm.vue
  src/vue/forms/market-orders/CreateTradeOfferForm.vue
  src/vue/forms/market-orders/SubmitTradeOfferForm.vue
  src/vue/forms/market-orders/YourTradeOfferForm.vue
  src/vue/mixins/offer-manager.mixin.js
  src/vue/modules/redeem-form/store/index.js
  src/vue/navigation/Passport.Balances.vue
  src/vue/pages/Dashboard.spec.js
  src/vue/pages/Dashboard.vue
  src/vue/pages/Fees.vue
  src/vue/pages/Limits.vue
  src/vue/pages/assets/AssetDetails.vue
  src/vue/pages/dashboard/Dashboard.AssetSelector.spec.js
  src/vue/pages/dashboard/Dashboard.AssetSelector.vue
  src/vuex/account.module.js
  src/vuex/account.spec.js
  src/vuex/assets.e2e.js
  src/vuex/assets.module.js
  src/vuex/assets.spec.js
  src/vuex/index.js
  src/vuex/types.js
  src/vuex/types.spec.js
Labels: enhancement

#361 [TDV-943] Update invest fees
  CHANGELOG.md
  src/i18n/en.json
  src/vue/forms/InvestForm.vue
Labels: bug, enhancement

#335 [TDV-417] Browser compatibility check
  .babelrc
  CHANGELOG.md
  src/i18n/en.json
  src/js/helpers/is-compatible-browser.js
  src/vue-router/router.js
  src/vue-router/routes.js
  src/vue/App.vue
  src/vue/common/WarningBanner.vue
  src/vue/pages/SupportedBrowsers.vue
Labels: enhancement
