Repository tokend/web-client, pull requests merged in 2019-06, with the labels that each got.

#246 [TDV-409] Unified fees calculation & displaying
  CHANGELOG.md
  src/i18n/en.json
  src/js/utils/math.util.js
  src/vue/common/fees/FeeViewer.vue
  src/vue/common/fees/FeesRenderer.vue
  src/vue/common/fees/fee.js
  src/vue/common/fees/fee.spec.js
  src/vue/common/fees/fees-collection.js
  src/vue/common/fees/fees-collection.spec.js
  src/vue/common/fees/fees.mixin.js
  src/vue/common/fees/fees.mixin.spec.js
  src/vue/forms/InvestForm.vue
  src/vue/forms/TransferForm.spec.js
  src/vue/forms/TransferForm.vue
  src/vue/forms/WithdrawalForm.vue
  src/vue/forms/market-orders/CreateTradeOfferForm.vue
  src/vue/forms/market-orders/SubmitTradeOfferForm.vue
  src/vue/forms/market-orders/YourTradeOfferForm.vue
  src/vue/mixins/offer-manager.mixin.js
  src/vue/modules/issuance-form/components/create-issuance-form.spec.js
  src/vue/modules/issuance-form/components/create-issuance-form.vue
  src/vue/modules/issuance-form/index.vue
Labels: enhancement

#351 [TDV-810] Move documents uploading to SDK
  CHANGELOG.md
  src/api.js
  src/i18n/en.json
  src/js/helpers/document-uploader.js
  src/js/helpers/error-handler.js
  src/js/helpers/upload-documents.js
  src/js/records/entities/asset.record.js
  src/js/records/entities/sale.record.js
  src/vue/App.vue
  src/vue/forms/LimitsDocumentsUploaderForm.vue
  src/vue/modules/assets/shared/components/logo-viewer.vue
  src/vue/modules/assets/shared/components/terms-viewer.vue
  src/vue/modules/assets/shared/wrappers/asset.js
  src/vue/modules/assets/shared/wrappers/asset.spec.js
  src/vue/modules/buy-back-form/wrappers/sale.record.js
  src/vue/modules/create-asset-form/index.vue
  src/vue/modules/create-asset-form/mixins/manage-asset-request.mixin.js
  src/vue/modules/create-asset-form/mixins/manage-asset-request.mixin.spec.js
  src/vue/modules/create-asset-form/mixins/upload-documents.mixin.js
  src/vue/modules/create-asset-form/mixins/upload-documents.mixin.spec.js
  src/vue/modules/create-opportunity/index.vue
  src/vue/modules/create-sale-form/mixins/manage-sale-request.mixin.js
  src/vue/modules/create-sale-form/mixins/manage-sale-request.mixin.spec.js
  src/vue/modules/create-sale-form/mixins/upload-documents.mixin.js
  src/vue/modules/create-sale-form/mixins/upload-documents.mixin.spec.js
  src/vue/modules/documents/document-upload-form/index.vue
  src/vue/modules/documents/document-upload-form/mixins/document-uploader.mixin.js
  src/vue/modules/requests/create-asset-requests/components/request-attributes-viewer.vue
  src/vue/modules/requests/create-asset-requests/components/request-viewer.vue
  src/vue/modules/requests/create-asset-requests/wrappers/create-asset-request.js
  src/vue/modules/requests/create-asset-requests/wrappers/create-asset-request.spec.js
  src/vue/modules/requests/create-sale-requests/components/request-viewer.vue
  src/vue/modules/requests/create-sale-requests/wrappers/asset.js
  src/vue/modules/requests/create-sale-requests/wrappers/asset.spec.js
  src/vue/modules/requests/create-sale-requests/wrappers/create-sale-request.js
  src/vue/modules/requests/create-sale-requests/wrappers/create-sale-request.spec.js
  src/vue/modules/requests/update-asset-requests/components/request-attributes-viewer.spec.js
  src/vue/modules/requests/update-asset-requests/components/request-attributes-viewer.vue
  src/vue/modules/requests/update-asset-requests/components/request-viewer.vue
  src/vue/modules/requests/update-asset-requests/wrappers/update-asset-request.js
  src/vue/modules/requests/update-asset-requests/wrappers/update-asset-request.spec.js
  src/vue/modules/update-asset-form/mixins/manage-asset-request.mixin.js
  src/vue/modules/update-asset-form/mixins/manage-asset-request.mixin.spec.js
  src/vue/modules/update-asset-form/mixins/upload-documents.mixin.js
  src/vue/modules/update-asset-form/mixins/upload-documents.mixin.spec.js
  src/vue/modules/verification/general-form/index.vue
  src/vue/modules/verification/general-form/store/index.js
  src/vue/modules/verification/general-form/store/upload-document-if-needed.js
  src/vue/pages/VerificationCorporate.vue
  src/vue/pages/VerificationGeneral.vue
  src/vue/pages/assets/AssetDetails.vue
  src/vue/pages/dashboard/Dashboard.AssetSelector.vue
  src/vue/pages/sale-details/SaleLogoViewer.vue
  src/vue/pages/sales/SaleCard.vue
  src/vue/pages/sales/SaleOverview.vue
Labels: enhancement

#366 [TDV-933] Status message improvements 3.5.0
  CHANGELOG.md
  src/scss/variables.scss
  src/vue/common/StatusMessage.vue
Labels: enhancement

#367 [TDV-936] Sale form improvements
  CHANGELOG.md
  src/i18n/en.json
  src/vue/modules/create-sale-form/components/information-step-form.spec.js
  src/vue/modules/create-sale-form/components/information-step-form.vue
  src/vue/modules/create-sale-form/mixins/load-asset-pairs.mixin.js
  src/vue/modules/create-sale-form/mixins/load-asset-pairs.spec.js
  src/vue/modules/create-sale-form/mixins/manage-sale-request.mixin.js
  src/vue/modules/create-sale-form/mixins/manage-sale-request.mixin.spec.js
  src/vue/modules/create-sale-form/wrappers/create-sale-request.js
Labels: enhancement

#368 [TDV-965] Move invest form to sale state widget
  CHANGELOG.md
  src/i18n/en.json
  src/vue/forms/InvestForm.vue
  src/vue/pages/OpportunityDetails.vue
  src/vue/pages/sale-details/SaleStateWidget.vue
Labels: enhancement

#374 [TDV-794] Allow the user to input birth date manually
  CHANGELOG.md
  src/i18n/en.json
  src/vue/fields/DateField.vue
  src/vue/modules/verification/general-form/components/section-personal.vue
Labels: enhancement

#375 [TDV-343] Format chart hints using SI prefixes
  CHANGELOG.md
  src/vue/common/chart/Chart.Renderer.vue
Labels: enhancement

#370 [TDV-890] Display incoming withdrawal request asset
  CHANGELOG.md
  src/i18n/en.json
  src/vue/modules/requests/incoming-withdrawal-requests/components/request-viewer.vue
  src/vue/modules/requests/incoming-withdrawal-requests/components/requests-table.vue
  src/vue/modules/requests/incoming-withdrawal-requests/store/index.js
  src/vue/modules/requests/incoming-withdrawal-requests/store/index.spec.js
  src/vue/modules/requests/incoming-withdrawal-requests/wrappers/incoming-withdrawal-request.js
  src/vue/modules/requests/incoming-withdrawal-requests/wrappers/incoming-withdrawal-request.spec.js
Labels: enhancement

#379 [TDV-208] Options-driven select field
  CHANGELOG.md
  package.json
  src/scss/app.scss
  src/vue/common/TradeTopBar.vue
  src/vue/fields/SelectField.vue
  src/vue/forms/DepositForm.vue
  src/vue/forms/InvestForm.vue
  src/vue/forms/LimitsForm.vue
  src/vue/forms/TransferForm.vue
  src/vue/forms/WithdrawalForm.vue
  src/vue/forms/market-orders/CreateTradeOfferForm.vue
  src/vue/modules/buy-back-form/index.vue
  src/vue/modules/create-asset-form/components/information-step-form.vue
  src/vue/modules/create-asset-form/mixins/manage-asset-request.mixin.js
  src/vue/modules/create-asset-form/mixins/manage-asset-request.mixin.spec.js
  src/vue/modules/create-opportunity/index.vue
  src/vue/modules/create-sale-form/components/information-step-form.vue
  src/vue/modules/create-sale-form/mixins/manage-sale-request.mixin.js
  src/vue/modules/create-sale-form/mixins/manage-sale-request.mixin.spec.js
  src/vue/modules/deposit-fiat-bank/index.vue
  src/vue/modules/deposit-fiat-card/index.vue
  src/vue/modules/dividend-form/index.vue
  src/vue/modules/issuance-form/components/create-issuance-form.vue
  src/vue/modules/movements-top-bar-reit/index.vue
  src/vue/modules/movements-top-bar/index.vue
  src/vue/modules/redeem-form/index.vue
  src/vue/modules/verification/general-form/components/section-country.vue
  src/vue/modules/verification/general-form/components/section-documents.vue
  src/vue/modules/withdrawal-fiat-bank/index.vue
  src/vue/modules/withdrawal-fiat-card/index.vue
  src/vue/pages/Dashboard.vue
  src/vue/pages/Fees.vue
  src/vue/pages/Limits.vue
  src/vue/pages/dashboard/Dashboard.AssetSelector.vue
  src/vue/pages/sales/SalesList.vue
  yarn.lock
Labels: enhancement

#377 [TDV-938] Add max button to amount input field
  CHANGELOG.md
  src/vue/fields/AmountInputField.vue
  src/vue/forms/TransferForm.vue
  src/vue/forms/WithdrawalForm.vue
  src/vue/modules/coinpayments-deposit/components/coinpayments-form.vue
  src/vue/modules/deposit-fiat-card/index.vue
Labels: enhancement

#369 [TDV-1002] Fix displaying selected asset on movements drawers
  CHANGELOG.md
  src/vue/forms/DepositForm.vue
  src/vue/forms/WithdrawalForm.vue
  src/vue/modules/movements-top-bar/index.vue
Labels: bug

#365 [TDQA-58, TDQA-85, TDQA-86, TDV-987] Fix 3.5.0 bugs
  CHANGELOG.md
  package.json
  src/i18n/en.json
  src/i18n/index.js
  src/i18n/index.spec.js
  src/js/utils/math.util.js
  src/main.js
  src/validators.js
  src/vue/fields/InputField.vue
  src/vue/filters/formatOrderNumber.js
  src/vue/filters/formatOrderNumber.spec.js
  src/vue/forms/InvestForm.vue
  src/vue/forms/TfaForm.vue
  src/vue/forms/market-orders/CreateTradeOfferForm.vue
  src/vue/forms/market-orders/SubmitTradeOfferForm.vue
  src/vue/forms/market-orders/YourTradeOfferForm.vue
  src/vue/modules/buy-back-form/index.vue
  src/vue/modules/create-asset-form/components/advanced-step-form.vue
  src/vue/modules/create-asset-form/components/information-step-form.vue
  src/vue/modules/create-opportunity/index.vue
  src/vue/modules/create-sale-form/components/information-step-form.vue
  src/vue/modules/dividend-form/index.vue
  src/vue/modules/issuance-form/components/create-issuance-form.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-form.vue
  src/vue/modules/withdrawal-fiat-bank/index.vue
  src/vue/modules/withdrawal-fiat-card/index.vue
  src/vue/pages/VerificationCorporate.vue
  yarn.lock
Labels: bug, enhancement

#381 [TDV-323] Add asset code validator
  CHANGELOG.md
  src/i18n/en.json
  src/validators.js
  src/vue/modules/create-asset-form/components/information-step-form.spec.js
  src/vue/modules/create-asset-form/components/information-step-form.vue
Labels: enhancement

#384 [TDV-1043] Fix 1.8.0 bugs
  CHANGELOG.md
  src/js/helpers/DocumentContainer.js
  src/vue/fields/AmountInputField.vue
  src/vue/fields/FileField.vue
  src/vue/fields/SelectField.vue
  src/vue/forms/DepositForm.vue
  src/vue/forms/InvestForm.vue
  src/vue/forms/TransferForm.vue
  src/vue/forms/market-orders/CreateTradeOfferForm.vue
  src/vue/forms/market-orders/SubmitTradeOfferForm.vue
  src/vue/forms/market-orders/YourTradeOfferForm.vue
  src/vue/modules/assets/asset-explorer/components/assets-renderer.vue
  src/vue/modules/assets/balance-explorer/index.spec.js
  src/vue/modules/assets/balance-explorer/index.vue
  src/vue/modules/assets/shared/components/card-viewer.vue
  src/vue/modules/create-asset-form/components/advanced-step-form.vue
  src/vue/modules/create-asset-form/components/information-step-form.vue
  src/vue/modules/create-opportunity/index.vue
  src/vue/modules/create-sale-form/components/information-step-form.vue
  src/vue/modules/dividend-form/index.vue
  src/vue/modules/fees/components/fees-table.vue
  src/vue/modules/issuance-form/components/create-issuance-form.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-form.vue
  src/vue/modules/withdrawal-fiat-bank/index.vue
  src/vue/modules/withdrawal-fiat-card/index.vue
  src/vue/pages/SaleDetails.vue
  src/vue/pages/sales/SalesList.vue
Labels: bug

#385 Hotfix: Displaying asset balance
  CHANGELOG.md
  src/vue/modules/assets/asset-explorer/components/assets-renderer.spec.js
  src/vue/modules/assets/asset-explorer/components/assets-renderer.vue
  src/vue/modules/assets/balance-explorer/index.spec.js
  src/vue/modules/assets/balance-explorer/index.vue
  src/vue/modules/assets/shared/components/asset-attributes-viewer.vue
Labels: bug

#388 Fix line breaks & update .gitattributes
  .gitattributes
  CHANGELOG.md
  static/android.png
  static/android_cropped.png
  static/app_store_cropped.png
  static/fonts/SourceSansPro/SourceSansPro-Black.woff
  static/fonts/SourceSansPro/SourceSansPro-ExtraLight.woff2
  static/fonts/SourceSansPro/SourceSansPro-Light.woff2
  static/google_play_cropped.png
  static/googleplay.png
  static/images/ios-install-guide/ios-install-guide__1.png
  static/images/ios-install-guide/ios-install-guide__2.png
  static/images/ios-install-guide/ios-install-guide__3.png
  static/images/ios-install-guide/ios-install-guide__4.png
  static/images/ios-install-guide/ios-install-guide__5.png
  static/images/ios-install-guide/ios-install-guide__6.png
  static/images/pre-issuance-guide/change-asset-issuer.png
  static/images/pre-issuance-guide/generate-new-keypair.png
  static/images/pre-issuance-guide/pre-issue-tokens.png
  static/images/pre-issuance-guide/settings-account-id-form.png
  static/images/pre-issuance-guide/settings-account-id-row.png
  static/images/pre-issuance-guide/settings-network-passphrase-form.png
  static/images/pre-issuance-guide/settings-network-passphrase-row.png
  static/iphone.png
  static/macosx_cropped.png
  static/pet-shop.png
  static/phones_overlay.png
  static/pre-issuance-app.png
  static/windows_cropped.png
Labels: bug, enhancement

#387 [TDV-966] Load latest KYC data using account endpoint
  CHANGELOG.md
  src/test/mocks/update-kyc.json
  src/vue/mixins/verification-form.mixin.js
  src/vue/modules/create-asset-form/components/information-step-form.vue
  src/vue/pages/VerificationCorporate.vue
  src/vue/pages/VerificationGeneral.vue
  src/vue/pages/VerificationGeneralAdvanced.vue
  src/vuex/kyc.e2e.js
  src/vuex/kyc.module.js
  src/vuex/kyc.spec.js
  src/vuex/types.js
Labels: enhancement

#390 [TDL-89] Loyalty changes
  CHANGELOG.md
  src/modules-arch/schemes/loyalty-points-merchant.en.json
  src/vue/App.vue
  src/vue/modules/loyalty-points/create-invoice-form/_config.js
  src/vue/modules/loyalty-points/create-invoice-form/components/balances-viewer.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/confirmation-state-viewer.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-confirmation.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-form.vue
  src/vue/modules/loyalty-points/create-invoice-form/components/invoice-state-viewer.vue
  src/vue/modules/loyalty-points/create-invoice-form/const/payment-states.const.js
  src/vue/modules/loyalty-points/create-invoice-form/index.vue
  src/vue/modules/loyalty-points/create-invoice-form/store/index.js
  src/vue/modules/loyalty-points/create-invoice-form/wrappers/invoice.js
  src/vue/modules/loyalty-points/loyalty-points-invoices/index.vue
  src/vue/pages/LoyaltyPoints.vue
  src/vuex/key-value.module.js
  src/vuex/types.js
Labels: enhancement, loyalty

#400 [TDV-1127] Fix tooltip displaying inside Drawer
  CHANGELOG.md
  src/vue/directives/tooltip.js
Labels: bug
